---
title: "Balancing economics with environmental and human health in the development of mariculture. "
---

Kuni Fellowship Proposal

Group members: Patricia Faundez-Baez, Owen Liu, Renato Molina, Molly Wilson

Faculty mentor: Ben Halpern

Research Questions: What are the economic incentives, environmental considerations, and human nutrition values driving the choice and production of maricultured species in the largest producer countries? 
Are there tradeoffs in mariculture production between profitability and environmental and human health?
Are there species currently not farmed that may better balance these tradeoffs than those currently produced?
Are there lessons arising from these tradeoffs that are relevant to other nations currently in the nascent stages of aquaculture development?

Significance: Aquaculture is the fastest-growing sector of food production in the world, growing at an astronomical annual average of 8.4 percent since 1970 (Hall 2011).  At the same time, global wild-capture fisheries production has leveled off since the mid-1990s.  As a result, over the past 50 years, aquaculture has become increasingly important in providing both an attractive source of economic rents and fish protein for human consumption (Subasinghe et al., 2009).  In 1962, aquaculture constituted just 5 percent of annual fish production for human consumption, but by 2012, this contribution had risen to 42 percent, and it is likely that over half of human fish consumption now comes from farmed species (FAO 2014).  In light of this growth, there is an urgent need to establish frameworks for assessing aquaculture relative to economic, environmental, and social priorities.
More than 500 species are farmed worldwide in fresh, brackish, and saltwater. We are focusing our assessment on mariculture species, those that are farmed in brackish and saltwater. Mariculture accounts for 71 farmed species (FAO 2014) and represents  about 35 percent of the world production harvest in 2012 (Fig.1), with a large scope for growth. 
Fish is a key source of protein and other essential nutrients, especially in the developing world. Of the 30 countries worldwide where fish accounts for more than one third of per capita annual protein, 22 are low-income, food deficit nations (Kawarazuka and Bene, 2011). Research has shown that marine foods carry nutritional characteristics that promote human health, highlighting not only fatty acids, but also other beneficial bioactive components and nutrients that differ in type and concentration from what is found in terrestrial sources (Lee et al., 2009). However, marine species display marked variability in nutritional content, and any assessment of mariculture should consider this variation. We will also consider environmental contaminants and human health hazards, such as the possible bioaccumulation of heavy metals in certain maricultured species (Yaktine et al., 2007). 
	Building a framework for prioritizing mariculture species is fundamentally an interdisciplinary endeavour.  Like fisheries, mariculture potential within a country is determined by the biology and ecology of its constituent species.  However, the realized production of any one species over time is often controlled by the economic dynamics of local, regional, and global markets.  Moreover, these biological and economic forces dynamically interact: strong economic incentives can drive changes in species’ fundamental biology through practices like selective breeding and genetic alteration.  Finally, the growth of mariculture globally has illuminated a number of ecological considerations and impacts, including the growing demand for fishmeal and fish oil, the impacts of escapement, disease, and genetic enhancement on local and regional wild stocks.
	The project team is well-equipped to draw on the expertise needed for the above. Owen and Molly are primarily marine ecologists with a focus on small scale fisheries and aligning social and ecological objectives.  Renato is both a theoretical and applied economist, and will be able to ensure that our project includes economic tools and robust economic analysis.  Patricia has a wealth of previous experience working with mariculture in Chile, and is also working actively on meta analysis and applying simple metrics to improve marine management.  She will bring both a practical perspective to our mariculture project, and the expertise in creating meaningful measures of mariculture feasibility.
With a global perspective and an interdisciplinary team, we will use existing data on species’ ecology, markets, and nutritional value to perform a multi-perspective evaluation of currently maricultured species, with a goal of shedding light on important economic, ecological, and human health tradeoffs.

Methods: 
A first step in our research process will be to choose appropriate countries for analysis (approximately 5 countries) based on current and potential mariculture production, development status, and data availability.  Our choice of countries will represent the diversity of mariculture systems across the developing world.

For each chosen case study, we will review literature and compile data on three components utilizing global datasets and regionally-specific scientific literature:
 
Economic: Mariculture economic production and trade statistics by species

Nutrition: Nutritional content of each farmed species, including: Protein, lipids and important fatty acids (e.g. EPA and DHAs), carbohydrates and fibres, vitamins and minerals, and other bioactive components (e.g., carotenoids, polyphenols, phytosterols and taurine).One of our suggested speakers, Sam Meyers, is an expert in human health associated with food production systems, and will be an important resource for compiling nutritional data.  Data will also be compiled for each species on potential nutritional hazards, including inorganic compounds such as methylmercury as well as persistent organic pollutants such as dioxins and polychlorinated biphenyls (PCBs).

Environmental impacts: We will develop environmental impact categories to rank maricultured species. Other resources already exist that can be adapted to our research directly, such as Trujillo’s (2008) Mariculture Sustainability Index, which ranks countries and their farmed species, based on six indicators: native vs. introduced; use of fishmeal; stocking density; larvae and seed provenance; habitat impacts, and waste treatment.

Next, we will develop the framework for prioritizing species based on economic, environmental, and human health criteria.  By developing these three sets of criteria separately, we will be able to illuminate the tradeoffs inherent between them.  We will be able to investigate, for example, why a species that makes sense economically is not ideal for development based on its expected environmental impacts and nutritional characteristics.  Moreover, the development of a common framework, but applied carefully to each case study separately, will allow for comparisons both within and among regions of interest, in order to draw general conclusions relevant to the rest of the world.

In addition to producing an academic publication, we are planning to communicate our results through publicly-accessible resources, such as an interactive web application for viewing country-specific results. 

Expected impacts: 
How society navigates future mariculture development has critical implications for local and global food security, economies, and environmental health. This study will provide a framework for assessing tradeoffs in these areas, and contribute to the responsible prioritization of species for future production.